package invoice_db;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.Set;

public class MainClass {
	public static void main(String[] args) throws ParseException {
		CustomerMasterDTO customermasterdto=new CustomerMasterDTO();
		customermasterdto.setCustomerno(1);
		customermasterdto.setCustomeraddress("Chennai");
		customermasterdto.setCustomeremail("ramu@gmail.com");
		customermasterdto.setCustomername("Ramu");
		customermasterdto.setCustomerphone("9876543210");
		CustomerMasterDAOImpl customermasterdaoimpl=new CustomerMasterDAOImpl(DBUtility.getConnection());
		customermasterdaoimpl.insertCustomer(customermasterdto);
		Set<CustomerMasterDTO> customerdetails=new HashSet<CustomerMasterDTO>();
		customerdetails=customermasterdaoimpl.getCustomerMasterAll();
		System.out.println(customerdetails);
		System.out.println(customermasterdaoimpl.getCustomerMaster(1));
		CustomerMasterDTO customermasterdtoupdate=new CustomerMasterDTO();
		customermasterdtoupdate.setCustomerno(1);
		customermasterdtoupdate.setCustomeraddress("Chennai");
		customermasterdtoupdate.setCustomeremail("somu@gmail.com");
		customermasterdtoupdate.setCustomername("Somu");
		customermasterdtoupdate.setCustomerphone("9876543210");
		customermasterdaoimpl.updateCustomer(customermasterdtoupdate);
		//customermasterdaoimpl.deleteCustomer(1);
		System.out.println("-----------------------");
		InvoiceMasterDTO invoicemasterdto=new InvoiceMasterDTO();
		invoicemasterdto.setCustomerno(1);
		invoicemasterdto.setInvdate("2021-01-01");
		InvoiceMasterDAOImpl invoicemasterdaoimpl=new InvoiceMasterDAOImpl(DBUtility.getConnection());
		invoicemasterdaoimpl.insertInvoice(invoicemasterdto);
		Set<InvoiceMasterDTO> invoicedetails=new HashSet<InvoiceMasterDTO>();
		invoicedetails=invoicemasterdaoimpl.getInvoiceMasterAll();
		System.out.println(invoicedetails);
		System.out.println(invoicemasterdaoimpl.getInvoiceMaster(101));
		InvoiceMasterDTO invoicemasterdtoupdate=new InvoiceMasterDTO();
		invoicemasterdtoupdate.setInvno(101);
		invoicemasterdtoupdate.setCustomerno(1);
		invoicemasterdtoupdate.setInvdate("2021-01-02");
		invoicemasterdaoimpl.updateInvoice(invoicemasterdtoupdate);
		//invoicemasterdaoimpl.deleteInvoice(1);
		System.out.println("--------------------");
		ItemMasterDTO itemmasterdto=new ItemMasterDTO();
		itemmasterdto.setItemdescription("MilkBikis");
		itemmasterdto.setItemprice(10);
		itemmasterdto.setItemunit("1 pkt");
		ItemMasterDAOImpl itemmasterdaoimpl=new ItemMasterDAOImpl(DBUtility.getConnection());
		itemmasterdaoimpl.insertItemDetails(itemmasterdto);
		Set<ItemMasterDTO> itemdetails=new HashSet<ItemMasterDTO>();
		itemdetails=itemmasterdaoimpl.getItemMasterAll();
		System.out.println(itemdetails);
		System.out.println(itemmasterdaoimpl.getItemMaster(1));
		ItemMasterDTO itemmasterdtoupdate=new ItemMasterDTO();
		itemmasterdtoupdate.setItemdescription("Parle - G");
		itemmasterdtoupdate.setItemprice(10);
		itemmasterdtoupdate.setItemunit("1 pkt");
		itemmasterdtoupdate.setItemno(1001);
		itemmasterdaoimpl.updateItemDetails(itemmasterdtoupdate);
		//itemmasterdaoimpl.deleteItemDetails(1001);
		System.out.println("--------------------");
		ItemTransactionMasterDTO itemtransactionmasterdto=new ItemTransactionMasterDTO();
		itemtransactionmasterdto.setItemno(1001);
		itemtransactionmasterdto.setInvno(101);
		itemtransactionmasterdto.setItemqty(2);
		ItemTransactionMasterDAOImpl itemtransactionmasterdaoimpl=new ItemTransactionMasterDAOImpl(DBUtility.getConnection());
		itemtransactionmasterdaoimpl.insertItem(itemtransactionmasterdto);
		Set<ItemTransactionMasterDTO> itemtransactiondetails=new HashSet<ItemTransactionMasterDTO>();
		itemtransactiondetails=itemtransactionmasterdaoimpl.getItemTransactionMasterAll();
		System.out.println(itemtransactiondetails);
		System.out.println(itemtransactionmasterdaoimpl.getItemTransactionMaster(101, 1001));
		ItemTransactionMasterDTO itemtransactionmasterdtoupdate=new ItemTransactionMasterDTO();
		itemtransactionmasterdtoupdate.setInvno(101);
		itemtransactionmasterdtoupdate.setItemno(1001);
		itemtransactionmasterdtoupdate.setItemqty(3);
		itemtransactionmasterdaoimpl.updateItem(itemtransactionmasterdtoupdate);
		//itemtransactionmasterdaoimpl.deleteItem(101, 1001);
		DBUtility.closeConnection(null);
	}
}
